apiVersion: v1
kind: Service
metadata:
  name: fe-svc
  labels:
    app: fems
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: fems
  loadBalancerIP: "35.195.207.240"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: fems
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fems
    spec:
      volumes:
      - name: ssl-volume
        secret:
          secretName: nginxsecret
      - name: fe-nginxconf
        configMap:
          name: fenginxconf
      - name: fe
        gitRepo:
          repository: "https://github.com/t5unamie/greenlab.git"
          revision: "715d6cbbff80519194a70bb7ec1e712f645d3f30"
      containers:
      - name: nginxhttps
        image: tsunamie/http-nginx:latest
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: fe
          subPath: "greenlab/02-frontend/01-MAIN"
        - mountPath: /etc/nginx/ssl
          name: ssl-volume
        - mountPath: /etc/nginx/conf.d
          name: fe-nginxconf