apiVersion: v1
kind: ConfigMap
metadata:
  name: fenginxconf
data:
  default.conf: |-
    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;
            server_name _;
            return 301 https://$host$request_uri;

            }
    server {
            listen 443 ssl;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            index index.html;
            root /usr/share/nginx/html/;

            location /static/ {
                if (-f $request_filename) {
                    break;
                }
                if (-d $request_filename) {
                    break;
                }
            }

            location / {

                add_header Access-Control-Allow-Origin "*" always;
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
                add_header Access-Control-Allow-Headers "content-type" always;

                # Handling the Preflight
                if ($request_method = OPTIONS ) {
                    return 200;
                }

                try_files $uri $uri/ /index.html?$uri&$args;
                if (-f $request_filename) {
                    break;
                }
                if (-d $request_filename) {
                    break;
                }
                rewrite ^(.+)$ /index.html?$1 last;
            }
    }   
