apiVersion: v1
kind: Service
metadata:
  name: fe-svc
  labels:
    app: fems
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: fems
  loadBalancerIP: "35.195.207.240"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: fems
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fems
    spec:
      volumes:
      - name: ssl-volume
        secret:
          secretName: nginxsecret
      - name: fe-nginxconf
        configMap:
          name: fenginxconf
      - name: fe
        gitRepo:
          repository: "https://github.com/t5unamie/greenlab.git"
          revision: "54f2a4a3f1417341a73ddcf1a6696829a2d49f29"
      containers:
      - name: nginxhttps
        image: tsunamie/http-nginx:latest
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: fe
          subPath: "greenlab/02-frontend/01-MAIN"
        - mountPath: /usr/share/nginx/images/
          name: fe
          subPath: "greenlab/Z-Assets/images"
        - mountPath: /etc/nginx/ssl
          name: ssl-volume
        - mountPath: /etc/nginx/conf.d
          name: fe-nginxconf