apiVersion: v1
kind: Service
metadata:
  name: secms-svc-proxy
  labels:
    app: secms-proxy
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: secms-proxy
  type: LoadBalancer
  loadBalancerIP: "35.205.81.190"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: secms-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: secms-proxy
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - name: nginxhttps
        image: tsunamie/http-nginx:latest
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume