apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
data:
  default.conf: |-
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=60r/m;
    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;

            listen 443 ssl;

            server_name localhost;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                    add_header Access-Control-Allow-Origin "*" always;
                    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
                    add_header Access-Control-Allow-Headers "Origin, Authorization" always;

                    # Handling the Preflight
                    if ($request_method = OPTIONS ) {
                        return 200;
                    }

                    limit_req zone=mylimit;
                    proxy_pass  http://securitysvc:3001;
            }
     }
